# Generated by Django 5.0.3 on 2024-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_project_remove_activites10_orientation1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites3_1',
            name='periode_prevue',
            field=models.CharField(max_length=100),
        ),
    ]
