# Generated by Django 5.0.3 on 2024-04-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites3_1',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites3_1', to='services.orientation3'),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='budget_prevu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='part_etat_burkinabe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='periode_prevue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='quantite_prevue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='responsable_projet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activites3_1',
            name='unite_physique',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
