# Generated by Django 5.0.3 on 2024-04-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_activites1_1_budget_prevu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites1_1',
            name='budget_prevu',
            field=models.IntegerField(null=True),
        ),
    ]
