# Generated by Django 5.0.3 on 2024-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_activites1_1_budget_prevu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activites1_1',
            name='budget_prevu',
        ),
    ]
