# Generated by Django 5.0.3 on 2024-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_activite_formulaire_orientation_projet_secteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='unite_physique',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
