# Generated by Django 5.0.3 on 2024-05-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_rename_periode_prevue_activite_periode_prevue_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_org', models.CharField(max_length=50, null=True)),
                ('nature_org', models.CharField(max_length=50, null=True)),
                ('sigle', models.CharField(max_length=50, null=True)),
                ('pays_origine', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('commune', models.CharField(max_length=100, null=True)),
                ('village', models.CharField(max_length=100, null=True)),
                ('boite_postale', models.CharField(max_length=50, null=True)),
                ('numb_mobile', models.CharField(max_length=50, null=True)),
                ('numb_fixe', models.CharField(max_length=50, null=True)),
                ('adresse_mail', models.CharField(max_length=50, null=True)),
                ('site_web', models.CharField(max_length=50, null=True)),
                ('nom_complet_resp', models.CharField(max_length=100, null=True)),
                ('nationalite_resp', models.CharField(max_length=50, null=True)),
                ('fonction_resp', models.CharField(max_length=50, null=True)),
                ('numb_fixe_resp', models.CharField(max_length=50, null=True)),
                ('numb_mobile_resp', models.CharField(max_length=50, null=True)),
                ('renou_instance', models.CharField(max_length=50, null=True)),
                ('assem_general', models.CharField(max_length=50, null=True)),
                ('session_statut', models.CharField(max_length=50, null=True)),
                ('mandat_bureau', models.CharField(max_length=50, null=True)),
                ('nom_complet_canevas', models.CharField(max_length=100, null=True)),
                ('numb_fixe_canevas', models.CharField(max_length=50, null=True)),
                ('numb_mobile_canevas', models.CharField(max_length=50, null=True)),
                ('adresse_mail_canevas', models.CharField(max_length=50, null=True)),
                ('objectifs', models.CharField(max_length=500, null=True)),
                ('groupes_cibles', models.CharField(max_length=200, null=True)),
                ('em_nation_cdi_homme', models.IntegerField(default=0)),
                ('em_nation_cdi_femme', models.IntegerField(default=0)),
                ('em_nation_cdd_homme', models.IntegerField(default=0)),
                ('em_nation_cdd_femme', models.IntegerField(default=0)),
                ('em_expa_cdi_homme', models.IntegerField(default=0)),
                ('em_expa_cdi_femme', models.IntegerField(default=0)),
                ('em_expa_cdd_homme', models.IntegerField(default=0)),
                ('em_expa_cdd_femme', models.IntegerField(default=0)),
                ('benevol_nation_homme', models.IntegerField(default=0)),
                ('benevol_nation_femme', models.IntegerField(default=0)),
                ('benevol_expa_homme', models.IntegerField(default=0)),
                ('benevol_expa_femme', models.IntegerField(default=0)),
                ('personnel_admin_homme', models.IntegerField(default=0)),
                ('personnel_admin_femme', models.IntegerField(default=0)),
                ('numb_convention', models.CharField(max_length=50, null=True)),
                ('date_debut_minis', models.CharField(max_length=50, null=True)),
                ('date_fin_minis', models.CharField(max_length=50, null=True)),
                ('numb_proto_collec', models.CharField(max_length=50, null=True)),
                ('date_debut_collec', models.CharField(max_length=50, null=True)),
                ('date_fin_collec', models.CharField(max_length=50, null=True)),
                ('numb_proto_convent', models.CharField(max_length=50, null=True)),
                ('date_debut_convent', models.CharField(max_length=50, null=True)),
                ('date_fin_convent', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
