# Generated by Django 5.0.3 on 2024-05-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_activiteplus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitePlus',
            new_name='ActivitePlu',
        ),
    ]
