# Generated by Django 5.0.3 on 2024-05-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_rename_activiteplus_activiteplu'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='id_activiteplus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_activiteplus', to='services.activiteplu'),
        ),
    ]
