# Generated by Django 5.0.3 on 2024-05-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_partenaire_id_activiteplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs', models.CharField(max_length=100, null=True)),
                ('id_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_general', to='services.infosgenerale')),
            ],
        ),
    ]
