# Generated by Django 5.0.3 on 2024-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_infosgenerale_objectifs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosgenerale',
            name='selected_collab',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
