# Generated by Django 5.0.3 on 2024-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_infosgenerale_selected_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
