# Generated by Django 5.0.3 on 2024-05-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_infosgenerale_selected_collab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteplu',
            name='budget_total',
        ),
    ]
