# Generated by Django 5.0.3 on 2024-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_partenariats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partenariats',
            new_name='Partenariat',
        ),
    ]
