# Generated by Django 5.0.3 on 2024-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_rename_partenariats_partenariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosgenerale',
            name='groupe_cible_total',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
